// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbCy4DtMr7tyy-eLxX2ns57DwQknuB7Aw',
    appId: '1:237711896721:web:23fc9533d00e3485398f30',
    messagingSenderId: '237711896721',
    projectId: 'dead-bot-app',
    authDomain: 'dead-bot-app.firebaseapp.com',
    storageBucket: 'dead-bot-app.appspot.com',
    measurementId: 'G-SEVLRLZBQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr5da7OVD7I2lcGuqFZr2cUW2PGYkat5M',
    appId: '1:237711896721:android:436d5421205fae42398f30',
    messagingSenderId: '237711896721',
    projectId: 'dead-bot-app',
    storageBucket: 'dead-bot-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjUzw53L4NRD9nheIQ-pJ26zWYub5oMek',
    appId: '1:237711896721:ios:d87b77e04454fc70398f30',
    messagingSenderId: '237711896721',
    projectId: 'dead-bot-app',
    storageBucket: 'dead-bot-app.appspot.com',
    androidClientId: '237711896721-m1tt1ti8s8j10t2j06c22h5vsdk4ejdu.apps.googleusercontent.com',
    iosBundleId: 'com.example.tewseelaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjUzw53L4NRD9nheIQ-pJ26zWYub5oMek',
    appId: '1:237711896721:ios:d87b77e04454fc70398f30',
    messagingSenderId: '237711896721',
    projectId: 'dead-bot-app',
    storageBucket: 'dead-bot-app.appspot.com',
    androidClientId: '237711896721-m1tt1ti8s8j10t2j06c22h5vsdk4ejdu.apps.googleusercontent.com',
    iosBundleId: 'com.example.tewseelaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbCy4DtMr7tyy-eLxX2ns57DwQknuB7Aw',
    appId: '1:237711896721:web:72b74c3622f9c038398f30',
    messagingSenderId: '237711896721',
    projectId: 'dead-bot-app',
    authDomain: 'dead-bot-app.firebaseapp.com',
    storageBucket: 'dead-bot-app.appspot.com',
    measurementId: 'G-2YCEH70WNN',
  );

}